[package]
name = "advent_of_code_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.13.0"
num = "0.4.3"
regex = "1.11.1"
thiserror = "2.0.7"
